groups:
    - name: custom_rules
      rules:
        - record: node_memory_MemFree_percent
          expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

    - name: uptime
      rules:
        - record: job:uptime:average:ft
          expr: avg without (instance) (up{job="forethought"})
        - alert: ForethoughtApplicationDown
          expr: job:uptime:average:ft < .75
          for: 30s
          labels:
            severity: page
            team: devops

     
    - name: alert_rules
      rules:
         - alert: InstanceDown
           expr: up == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: 'Instance {{ $labels.instance }} down'
             description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'

         - alert: DiskSpaceFree10Percent
           expr: node_filesystem_free_percent <= 10
           labels:
               severity: warning
           annotations:
               summary: 'Instance {{ $labels.instance }} has 10% or less Free disk space'
               description: '{{ $labels.instance }} has only {{ $value }}% or less free.'

